name: lint-test-deploy

on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Lint code
              run: eslint . --ext .js, .jsx, .ts, .tsx
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Run vite tests
              run: vitest run
    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: build
              uses: vite build
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: deploy
              run: echo "app has deployed"